config/routes.rb
Depotalternative::Application.routes.draw do

  get "click/new"

  get "states/index"

  get "states/new"

  get "admins/index"
  
  resources :favorites, :only => [:index, :create, :destroy]
  
  devise_for :users, :path_prefix => 'd'
  resources :users
  

  match '/cities/for_stateid/:state_id' => 'cities#for_stateid'

  devise_for :users, :path_prefix => 'd'
  resources :users
  resources :states
  resources :suppliers
  match 'suppliers/:id/print'  => 'suppliers#show', :as => :print_supplier
  match 'about' => 'suppliers#about'
  resources :cities
  resources :specialties

  match ':controller/:action/:id'
  

  root :to => "suppliers#index"

end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities
end

app/controllers/states_controller.rb
class StatesController < ApplicationController

  load_and_authorize_resource

      # GET /states
      # GET /states.xml
      def index
        @states = State.all

        respond_to do |format|
          format.html # index.html.erb
          format.xml  { render :xml => @states }
        end
      end

      # GET /states/1
      # GET /states/1.xml
      def show
        @state = State.find(params[:id])

        respond_to do |format|
          format.html # show.html.erb
          format.xml  { render :xml => @state }
        end
      end

      # GET /states/new
      # GET /states/new.xml
      def new
        @state = State.new

        respond_to do |format|
          format.html # new.html.erb
          format.xml  { render :xml => @state }
        end
      end

      # GET /states/1/edit
      def edit
        @state = State.find(params[:id])
      end

      # POST /states
      # POST /states.xml
      def create
        @state = State.new(params[:state])

        respond_to do |format|
          if @state.save
            format.html { redirect_to(@state, :notice => 'State was successfully created.') }
            format.xml  { render :xml => @state, :status => :created, :location => @city }
          else
            format.html { render :action => "new" }
            format.xml  { render :xml => @state.errors, :status => :unprocessable_entity }
          end
        end
      end

      # PUT /states/1
      # PUT /states/1.xml
      def update
        @state = State.find(params[:id])

        respond_to do |format|
          if @state.update_attributes(params[:state])
            format.html { redirect_to(@state, :notice => 'State was successfully updated.') }
            format.xml  { head :ok }
          else
            format.html { render :action => "edit" }
            format.xml  { render :xml => @state.errors, :status => :unprocessable_entity }
          end
        end
      end

      # DELETE /states/1
      # DELETE /states/1.xml
      def destroy
        @state = State.find(params[:id])
        @state.destroy

        respond_to do |format|
          format.html { redirect_to(states_url) }
          format.xml  { head :ok }
        end
      end


end

app/helpers/state_helper.rb
module StateHelper
end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br />
    <%= f.text_field :abbreviation %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<h1>Listing states</h1>

<table>
  <tr>
    <th>State Name
    <th>Abbreviation</th>
  </tr>

<% @states.each do |state| %>
  <tr>
    <td><%= state.name %></td>
    <td><%= state.abbreviation %></td>

    <td><%= link_to 'Show', state %></td>
    <td><%= link_to 'Edit', edit_state_path(state) %></td>
    <td><%= link_to 'Destroy', state, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<h1>Listing cities in <%= @state.name %></h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @state.name %>
</p>

<p>
  <b>Abbreviation:</b>
  <%= @state.abbreviation %>
</p>



<% if @state.cities.size == 0 %>
    <p>
    There are no cities listed for this state.
    </p>
<% else %>
    <table>
        <tr>
        <th>City Name</th>
        <th></th>
        <th></th>
        <th></th>
        </tr>

        <% @state.cities.each do |city| %>
          <tr>
            <td><%= city.city_name %></td>
            <td><%= link_to 'Show', city %></td>
            <td><%= link_to 'Edit', edit_city_path(city) %></td>
            <td><%= link_to 'Destroy', city, :confirm => 'Are you sure?', :method => :delete %></td>
          </tr>
        <% end %>
    </table>
<% end %>


<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>