config/routes.rb
Depotalternative::Application.routes.draw do

  get "click/new"

  get "states/index"

  get "states/new"

  get "admins/index"
  
  resources :favorites, :only => [:index, :create, :destroy]
  
  devise_for :users, :path_prefix => 'd'
  resources :users
  

  match '/cities/for_stateid/:state_id' => 'cities#for_stateid'

  devise_for :users, :path_prefix => 'd'
  resources :users
  resources :states
  resources :suppliers
  match 'suppliers/:id/print'  => 'suppliers#show', :as => :print_supplier
  match 'about' => 'suppliers#about'
  resources :cities
  resources :specialties

  match ':controller/:action/:id'
  

  root :to => "suppliers#index"

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :suppliers
  belongs_to :state

  validates_presence_of :city_name
  validates_presence_of :state
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    
    load_and_authorize_resource
  
    # GET /cities
    # GET /cities.xml
    def index
      @cities = City.all

      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @cities }
      end
    end

    # GET /cities/1
    # GET /cities/1.xml
    def show
      @city = City.find(params[:id])
      @state = State.find(@city.state_id)

      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @city }
      end
    end

    # GET /cities/new
    # GET /cities/new.xml
    def new
      @city = City.new

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @city }
      end
    end

    # GET /cities/1/edit
    def edit
      @city = City.find(params[:id])
    end

    # POST /cities
    # POST /cities.xml
    def create
      @city = City.new(params[:city])
      @state = State.find(params[:state_id])

      respond_to do |format|
        if @state.cities << @city
          format.html { redirect_to(@city, :notice => 'City was successfully created.') }
          format.xml  { render :xml => @city, :status => :created, :location => @city }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @city.errors, :status => :unprocessable_entity }
        end
      end
    end

    # PUT /cities/1
    # PUT /cities/1.xml
    def update
      @city = City.find(params[:id])

      respond_to do |format|
        if @city.update_attributes(params[:city])
          format.html { redirect_to(@city, :notice => 'City was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @city.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /cities/1
    # DELETE /cities/1.xml
    def destroy
      @city = City.find(params[:id])
      @city.destroy

      respond_to do |format|
        format.html { redirect_to(cities_url) }
        format.xml  { head :ok }
      end
    end

    def for_stateid
      @cities = City.find_all_by_state_id(params[:state_id]).sort_by{ |k| k['city_name']}
      respond_to do |format|
        format.json  { render :json => @cities }
      end
    end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city_name %><br />
    <%= f.text_field :city_name %>
  </div>
  <div class="field">
    <br>
    <%= f.label :state_id %> <br />
    <%= f.collection_select :state_id, State.all, :id, :name%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <tr>
    <th>City Name
    <th>State</th>
  </tr>

<% @cities.each do |city| %>
  <tr>
    <td><%= city.city_name %></td>
    <td><%= State.find(city.state_id).name %></td>

    <td><%= link_to 'Show', city %></td>
    <td><%= link_to 'Edit', edit_city_path(city) %></td>
    <td><%= link_to 'Destroy', city, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<h1>Listing suppliers in <%= @city.city_name %>, <%= @state.name %></h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @city.city_name %>
</p>

<p>
  <b>State:</b>
  <%= @state.name %>
</p>



<% if @city.suppliers.size == 0 %>
    <p>
    There are no suppliers for this city.
    </p>
<% else %>
    <table>
        <tr>
        <th>Name
        <th>City</th>
        <th>State</th>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
        </tr>

        <% @city.suppliers.each do |supplier| %>
          <tr>
            <td><%= supplier.name %></td>
            <td><%= supplier.description %></td>
            <td><%= link_to 'Show', supplier %></td>
            <td><%= link_to 'Edit', edit_supplier_path(supplier) %></td>
            <td><%= link_to 'Destroy', supplier, :confirm => 'Are you sure?', :method => :delete %></td>
          </tr>
        <% end %>
    </table>
<% end %>


<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>