config/routes.rb
Depotalternative::Application.routes.draw do

  get "click/new"

  get "states/index"

  get "states/new"

  get "admins/index"
  
  resources :favorites, :only => [:index, :create, :destroy]
  
  devise_for :users, :path_prefix => 'd'
  resources :users
  

  match '/cities/for_stateid/:state_id' => 'cities#for_stateid'

  devise_for :users, :path_prefix => 'd'
  resources :users
  resources :states
  resources :suppliers
  match 'suppliers/:id/print'  => 'suppliers#show', :as => :print_supplier
  match 'about' => 'suppliers#about'
  resources :cities
  resources :specialties

  match ':controller/:action/:id'
  

  root :to => "suppliers#index"

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  attr_accessible :city_id, :specialty_id, :uploaded_file, :name, :description, :address, :phone_number, :email

  belongs_to :city
  belongs_to :specialty
  belongs_to :user

  has_many :clicks

  validates :name, :city_id, :specialty_id, :presence => true

  validates_each :user do |supplier, attr, value|
    supplier.errors.add attr, "You can only create one listing." if supplier.user.suppliers.size >= 1
  end

  #set up "uploaded_file" field as attached_file (using Paperclip)
  has_attached_file :uploaded_file,
                    :path => "suppliers/:id/:style/:basename.:extension",
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/amazon_s3.yml",
                    :bucket => "depotalternative",
                    :styles => {
                        :thumbnail => "150x150>",
                        :normal    => "800x800>"
                    }


  validates_attachment_size :uploaded_file, :less_than => 10.megabytes
  #validates_attachment_presence :uploaded_file
  validates_attachment_content_type :uploaded_file, :content_type => ['image/jpeg', 'image/png', 'image/gif']

  def file_name
    uploaded_file_file_name
  end

  def self.filter(state_id, city_id, specialty_id, per_page, page)

      #IF NOT CHOOSE A STATE, RETURN ALL SUPPLIERS EVERYWHERE
    if state_id != nil && state_id != '--Select a State--'
       @state = State.find(state_id)
       #IF CHOOSE STATE, GET CITIES OF THAT STATE
       @cities = @state.cities
       #IF CITY SELECTED, GET SUPPLIERS FOR THAT CITY AND STATE ONLY
       if city_id != nil && city_id != ''
         @chosen_city = City.find_by_id(city_id)
         #IF SPECIALTY SELECTED, GET SUPPLIERS WITH THAT SPECIALTY ONLY IN THAT CITY AND STATE
         if specialty_id != nil && specialty_id != ''
           if @cities.include?(@chosen_city)
             find_by_sql("SELECT * FROM suppliers WHERE city_id = " + @chosen_city.id.to_s + " AND specialty_id = " + specialty_id).paginate(:per_page => per_page, :page => page)
           else
             find_by_sql("SELECT * FROM suppliers s, cities c WHERE s.city_id = c.id AND c.state_id = " + @state.id.to_s + " AND specialty_id = " + specialty_id).paginate(:per_page => per_page, :page => page)
           end
         else
           #TEMPORARY SOLUTION UNTIL REFRESH CITY DROPDOWN ON STATE CHANGE
           if @cities.include?(@chosen_city)
             @chosen_city.suppliers.paginate(:per_page => per_page, :page => page)
           else
             find_by_sql("SELECT * FROM suppliers s, cities c WHERE s.city_id = c.id AND c.state_id = " + @state.id.to_s).paginate(:per_page => per_page, :page => page)
           end
         end

       #IF NO CITY SELECTED AND SPECIALTY SELECTED, DISPLAY SUPPLIERS WITH THAT SPECIALTY IN THAT STATE
       elsif specialty_id != nil && specialty_id != ''
         find_by_sql("SELECT * FROM suppliers s, cities c WHERE s.city_id = c.id AND c.state_id = " + @state.id.to_s + " AND s.specialty_id = " + specialty_id).paginate(:per_page => per_page, :page => page)
       #IF NO CITY OR SPECIALTY SELECTED, RETURN ALL SUPPLIERS IN SELECTED STATE
       else
          find_by_sql("SELECT * FROM suppliers s, cities c WHERE s.city_id = c.id AND c.state_id = " + @state.id.to_s).paginate(:per_page => per_page, :page => page)
       end
    elsif specialty_id != nil && specialty_id != ''
      find_all_by_specialty_id(specialty_id).paginate(:per_page => per_page, :page => page)
    else
      all.paginate(:per_page => per_page, :page => page)
    end
  end

  def self.get_results(state_id, city_id, specialty_id)
     if state_id != nil && state_id != '--Select a State--'
       #IF CHOOSE STATE, GET CITIES OF THAT STATE
       @state = State.find(state_id)
       @cities = @state.cities

       #IF CITY SELECTED, GET SUPPLIERS FOR THAT CITY AND STATE ONLY
       if city_id != nil && city_id != ''
         @chosen_city = City.find_by_id(city_id)
         #IF SPECIALTY SELECTED, GET SUPPLIERS WITH THAT SPECIALTY ONLY IN THAT CITY AND STATE
         if specialty_id != nil && specialty_id != ''
            @results = "Showing " + Specialty.find_by_id(specialty_id).name + " Suppliers in " + @chosen_city.city_name + ", " + @state.name
         else
           #TEMPORARY SOLUTION UNTIL REFRESH CITY DROPDOWN ON STATE CHANGE
           if @cities.include?(@chosen_city)
             @results = "Showing All Suppliers in " + @chosen_city.city_name + ", " + @state.name
           else
             @results = "Showing All Suppliers in " + @state.name
           end
         end

       #IF NO CITY SELECTED AND SPECIALTY SELECTED, DISPLAY SUPPLIERS WITH THAT SPECIALTY IN THAT STATE
       elsif specialty_id != nil && specialty_id != ''
         @results = "Showing " + Specialty.find_by_id(specialty_id).name + " Suppliers in " + @state.name
       #IF NO CITY OR SPECIALTY SELECTED, RETURN ALL SUPPLIERS IN SELECTED STATE
       else
          @results = "Showing All Suppliers in " + @state.name
       end
    elsif specialty_id != nil && specialty_id != ''
      @results = "Showing " + Specialty.find_by_id(specialty_id).name + " Suppliers in All Cities"
    else
      @results = "Showing All Suppliers in All Cities"
    end
    return @results
  end

  #if states != nil && states != '--Select a State--'
       #IF CHOOSE STATE, GET CITIES OF THAT STATE
  #     @cities = City.find_all_by_state(states)
       #IF CITY SELECTED, GET SUPPLIERS FOR THAT CITY AND STATE ONLY
  #     if city_id != nil && city_id != ''
  #       @chosen_city = City.find_by_id(city_id)
  #       #IF SPECIALTY SELECTED, GET SUPPLIERS WITH THAT SPECIALTY ONLY IN THAT CITY AND STATE
  #       if specialty_id != nil && specialty_id != ''
  #         @suppliers = Supplier.find_by_sql("SELECT * FROM suppliers WHERE city_id = " + @chosen_city.id.to_s + " AND specialty_id = " + specialty_id).paginate(:per_page => @per_page, :page => params[:page])
  #         @results = "Showing " + Specialty.find_by_id(params[:specialty_id]).name + " Suppliers in " + @chosen_city.city_name + ", " + params[:states]
  #       else
  #         #TEMPORARY SOLUTION UNTIL REFRESH CITY DROPDOWN ON STATE CHANGE
  #         if @cities.include?(@chosen_city)
  #           @results = "Showing All Suppliers in " + @chosen_city.city_name + ", " + params[:states]
  #           @suppliers = @chosen_city.suppliers.paginate(:per_page => @per_page, :page => params[:page])
  #         else
  #           @suppliers = Supplier.find_by_sql("SELECT * FROM suppliers s, cities c WHERE s.city_id = c.id AND c.states = '" + params[:states] + "'").paginate(:per_page => @per_page, :page => params[:page])
  #           @results = "Showing All Suppliers in " + params[:states]
  #         end
  #       end
  #
  #     #IF NO CITY SELECTED AND SPECIALTY SELECTED, DISPLAY SUPPLIERS WITH THAT SPECIALTY IN THAT STATE
  #     elsif params[:specialty_id] != nil && params[:specialty_id] != ''
  #       @suppliers = Supplier.find_by_sql("SELECT * FROM suppliers s, cities c WHERE s.city_id = c.id AND c.states = '" + params[:states] + "' AND s.specialty_id = " + params[:specialty_id]).paginate(:per_page => @per_page, :page => params[:page])
  #       @results = "Showing " + Specialty.find_by_id(params[:specialty_id]).name + " Suppliers in " + params[:states]
  #     #IF NO CITY OR SPECIALTY SELECTED, RETURN ALL SUPPLIERS IN SELECTED STATE
  #     else
  #        @suppliers = Supplier.find_by_sql("SELECT * FROM suppliers s, cities c WHERE s.city_id = c.id AND c.states = '" + params[:states] + "'").paginate(:per_page => @per_page, :page => params[:page])
  #        @results = "Showing All Suppliers in " + params[:states]
  #     end
  #  elsif params[:specialty_id] != nil && params[:specialty_id] != ''
  #    @suppliers = Supplier.find_all_by_specialty_id(params[:specialty_id]).paginate(:per_page => @per_page, :page => params[:page])
  #    @results = "Showing " + Specialty.find_by_id(params[:specialty_id]).name + " Suppliers in All Cities"
  #  else
  #    @results = "Showing All Suppliers in All Cities"
  #    @suppliers = Supplier.all.paginate(:per_page => @per_page, :page => params[:page])
  #  end

end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  load_and_authorize_resource
  
  layout :choose_layout
  
  # GET /suppliers
  # GET /suppliers.xml
  
  before_filter :authenticate_user!, :except=> [:show, :index]
  
  def index

    @specialties = Specialty.all
    @suppliers = Supplier.filter(params[:state_id], params[:city_id], params[:specialty_id], 20, params[:page])
    @results = Supplier.get_results(params[:state_id], params[:city_id], params[:specialty_id])
    @states = State.all
    @cities = City.find_all_by_state_id(params[:state_id])

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.xml  { render :xml => @suppliers }
    end
  end
  
  def about
    @specialties = Specialty.all
  end


  # GET /suppliers/1
  # GET /suppliers/1.xml
  def show
    @supplier = Supplier.find(params[:id])

    @click = Click.new(@supplier.id)

    if @supplier.clicks << @click
      @clicks_this_month = Click.clicks_this_month Date.today


      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @supplier }
      end
    end
  end
  
  # GET /suppliers/1
  # GET /suppliers/1.xml
  def print
    @supplier = Supplier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @supplier }
    end
  end

  # GET /suppliers/new
  # GET /suppliers/new.xml
  def new
    @states = State.all
    @cities = City.find_all_by_state_id(params[:id])
    @supplier = current_user.suppliers.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @supplier }
    end
  end


  # GET /suppliers/1/edit
  def edit
    @supplier = current_user.suppliers.find(params[:id])
    @state = State.find(@supplier.city.state)
    @cities = City.find_all_by_state_id(@state.id)
    @states = State.all
  end

  # POST /suppliers
  # POST /suppliers.xml
  def create
    @supplier = current_user.suppliers.new(params[:supplier])
    @specialty = Specialty.find(@supplier.specialty_id)
    @city = City.find(@supplier.city_id)

    respond_to do |format|
      if @city.suppliers << @supplier && @specialty.suppliers << @supplier
        format.html { redirect_to(@supplier, :notice => 'Supplier was successfully created.') }
        format.xml  { render :xml => @supplier, :status => :created, :location => @supplier }
      else
        #@states = State.all
        #@cities = City.find_all_by_state_id(params[:state_id])
        format.html { render :action => "new" }
        format.xml  { render :xml => @supplier.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /suppliers/1
  # PUT /suppliers/1.xml
  def update
    @supplier = Supplier.find(params[:id])
    @city = City.find(@supplier.city_id)
    @specialty = Specialty.find(@supplier.specialty_id)

    respond_to do |format|
      if @supplier.update_attributes(params[:supplier]) #&& @city.suppliers << @supplier && @specialty.suppliers << @supplier
        format.html { redirect_to(@supplier, :notice => 'Supplier was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @supplier.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.xml
  def destroy
    @supplier = current_user.suppliers.find(params[:id])
    @supplier.destroy

    respond_to do |format|
      format.html { redirect_to(suppliers_url, :notice => 'Supplier was successfully deleted.') }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def choose_layout
    if current_user && params[:print] == "true"
      "print"
    else
      "application"
    end
  end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_cities.erb
<% if @cities %>
  <%= collection_select @filter, :city_id, @cities, :id, :city_name, {:id => 'city_search', :selected => params[:city_id], :prompt => '--Select a City--'}, {:onchange => "$('#suppliers_search').submit()"}%>
<% end %>

app/views/suppliers/_form.html.erb
<script type="text/javascript">
    $(document).ready(function(){
        $("select#supplier_state_id").change(function(){
            var id_value_string = $(this).val();
            if (id_value_string == "") {
                // if the id is empty remove all the sub_selection options from being selectable and do not do any ajax
                $("select#supplier_city_id option").remove();
                var row = "<option value=\"" + "" + "\">" + "--No Cities--" + "</option>";
                $(row).appendTo("select#supplier_city_id");
            }
            else {
                // Send the request and update sub category dropdown
                $.ajax({
                    dataType: "json",
                    cache: false,
                    url: '/cities/for_stateid/' + id_value_string,
                    timeout: 2000,
                    error: function(XMLHttpRequest, errorTextStatus, error){
                        alert("Failed to submit : "+ errorTextStatus+" ;"+error);
                    },
                    success: function(data){
                        // Clear all options from sub category select
                        $("select#supplier_city_id option").remove();
                        //put in a empty default line
                        var row = "<option value=\"" + "" + "\">" + "--Select a City--" + "</option>";
                        $(row).appendTo("select#supplier_city_id");
                        // Fill sub category select
                        $.each(data, function(i, j){
                            row = "<option value=\"" + j.city.id + "\">" + j.city.city_name + "</option>";
                            $(row).appendTo("select#supplier_city_id");
                        });
                     }
                });
            };
                });
    });
</script>

<%= form_for(@supplier, :html=>{:multipart=>true}) do |f| %>
  <% if @supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
      <% @supplier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset>
		<ul>
			<li>
				<label for="position">Name:</label>
				<div><%= f.text_field :name %></div>
				<div>Example:  Jim's Hardware</div>
			</li>
		</ul>
	</fieldset>
	
	<fieldset>
		<ul>
			<li>
				<label for="position">Address:</label>
				<div><%= f.text_field :address %></div>
				<div>Example:  123 Oak Grove Rd.</div>
			</li>
		</ul>
	</fieldset>

    <fieldset>
        <ul>
            <li>
                <label for="position">State:</label>
                <% if @state %>
                  <div><%= collection_select :supplier, :state_id, @states, :id, :name, {:selected => @state.id, :prompt => '--Select a State--'} %></div>
                <% else %>
                  <div><%= collection_select(:supplier, :state_id, @states, :id, :name, {:prompt => '--Select a State--'}) %></div>
                <% end %>
              <div>Example:  Alabama</div>
            </li>
        </ul>
    </fieldset>

    <fieldset>
        <ul>
            <li>
                <label for="position">City:</label>
                <div><%= collection_select :supplier, :city_id, @cities, :id, :city_name, {:prompt => '--Select a City--'} %></div>
                <div>Example:  Montgomery</div>
            </li>
        </ul>
    </fieldset>

	<fieldset>
		<ul>
			<li>
				<label for="position">Specialty:</label>
				<div><%= f.collection_select :specialty_id, Specialty.all, :id, :name%></div>
				<div>Choose from out list of specialties.  Don't see what you're looking for?  Send us some <%= link_to "feedback", "http://getsatisfaction.com/depotalternative" %> and we'll add it to our list.</div>
			</li>
		</ul>
	</fieldset>


  	<fieldset>
		<ul>
			<li>
				<label for="position">Phone:</label>
				<div><%= f.text_field :phone_number %></div>
				<div>Example:  123-456-7890</div>
			</li>
		</ul>
	</fieldset>
	
	<fieldset>
		<ul>
			<li>
				<label for="position">Email:</label>
				<div><%= f.text_field :email %></div>
				<div>Example:  ryan@something.com</div>
			</li>
		</ul>
	</fieldset>
 
	<fieldset>
		<ul>
			<li>
				<label for="position">Description:</label>
				<div><%= f.text_area :description %></div>
				<div>
					Tells us about your company/store.  Tell your customers why you're special and should use your company for their next project.
				</div>
			</li>
		</ul>
	</fieldset>

	<fieldset>
		<ul>
			<li>
				<label for="position">Picture:</label>
				<div><%= f.file_field :uploaded_file %></div>
				<div>
					Upload a picture of a job you've completed or your store.  Make sure your picture is a good representation of who you are or how you want to be portrayed.  You can always change this after you have created your listing.
				</div>
			</li>
		</ul>
	</fieldset>

  <div id="action">
    <%= f.submit %>
  </div>
<% end %>

app/views/suppliers/_states.erb
<% if @states %>
  <%= collection_select @filter, :state_id, @states, :id, :name, {:id => 'state_search', :selected => params[:state_id], :prompt => '--Select a State--'}, {:onchange => "$('#suppliers_search').submit()"}%>
<% end %>

app/views/suppliers/_suppliers.erb
<ul id="listings">
<% if @suppliers.count > 0 %>
    <% @suppliers.each do |supplier| %>
    <li class="<%= cycle('even', 'odd') %>">
        <%= link_to supplier do %>
            <span>
                <div class="type <%=supplier.specialty.name  %>"><%= supplier.specialty.name %></div>
                <div class="role">
                    <h3><%= supplier.name %></h3>
                     <span><%= truncate(supplier.description, :length => 40) %></span>
                </div>
                <span class="location">
                    <%= supplier.city.city_name %>, <%= supplier.city.state.name %>
                </span>
            </span>
        <% end %>
    </li>
    <% end %>
<% end %>

</ul>
<%= will_paginate @suppliers %>

app/views/suppliers/about.html.erb
<div id="about"><h2>Depot Alternative helps you find local construction suppliers for your next big project.</div>
<div id="clear"></div>
<div class="heading">
	<%= image_tag "map_big.png", :class=>"about_map_icon"%>
	<h3>Find a local supplier</h3>
	<p>Find by city, state or supplier type.  Check out pictures of their work or products.  Save to favorites or share with friends.</p>
	<p><%= link_to 'Find a supplier', root_path %></p>
</div>

<div class="heading">
	<%= image_tag "phone_big.png", :class=>"about_map_icon"%>
	<h3>Suppliers, join the club!</h3>
	<p>Add your store to the directory. Create a profile and upload images.  Attract more customers and build your business. </p>
	<%= link_to 'Create your listing', new_supplier_path, :class=>"button" %>
</div>

<div id="clear"></div>

<div id="about_specialties">
	<div id="about"><h2>These are the specialties we support.  Don't see one you need? <%= link_to "Let us know", "http://getsatisfaction.com/depotalternative" %>.</div>

	<table id="specialties">
		<%= render :partial=>"specialties/specialties", :object=>@specialties %>
	</table>
</div>

app/views/suppliers/edit.html.erb
<h1>Editing supplier</h1>

<%= render 'form' %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %> |
<%= link_to 'Destroy', @supplier, :confirm => 'Are you sure?', :method => :delete %>

app/views/suppliers/index.html.erb
<div id="supplier_filter_search">

    <h5>Narrow down the suppliers:</h5>
	<span class="filter_form">
	    <%= form_tag "/suppliers", :method => 'get', :id => 'suppliers_search' do  %>
	      <%= render 'states' %>
	      <span id='city_search_wrapper'><%= render 'cities' %></span>
	      <% if @specialties %>
	          <%= collection_select @filter, :specialty_id, @specialties, :id, :name, {:selected => params[:specialty_id], :prompt => '--Select a Specialty--'}, {:onchange => "$('#suppliers_search').submit()"}%>
	      <% end %>
	    <% end %>
	</span>
</div>

<div id="suppliers_wrapper">
  <%= render 'suppliers' %>
</div>

app/views/suppliers/index.js.erb
$("#suppliers_wrapper").html("<%= escape_javascript(render("suppliers")) %>");

$("#city_search_wrapper").html("<%= escape_javascript(render("cities")) %>");

app/views/suppliers/new.html.erb
<div class="title_header"><h1>Create your new listing ...</h1></div>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<div id="supplier_header">
	<div class="name">
		<div><h2><%= @supplier.name %></h2> 
			<% if can? :modify, @supplier %>
		  		<%= link_to "Edit", edit_supplier_path(@supplier) %>
			<% end %>
		</div>
		<div class="city_state"><%= @supplier.city.city_name %>, <%= @supplier.city.state.name %></div>
	</div>
	
	<% if current_user %>
		<div class="favorite"><%= link_to 'Favorite', favorites_path(:id=>@supplier), :method => :post %></div>
		<div class="share">Share</div>
		<div class="print"><%= link_to "Print", supplier_path(@supplier, :print=>true) %></div>			
	<% else %>
		<div class="login"><%= link_to 'Sign in', new_user_session_path %> for options</div>
	<% end %>

</div>

<div id="clear"></div>

<div id="supplier_body">
	<div><span class="type <%= @supplier.specialty.name %>"><%= @supplier.specialty.name %></span></div>
	<div id="clear"></div>
	<div class="description"><%= @supplier.description %></div>

	<div class="contact_info">
		<h2>Get in touch</h2>
		<% if current_user %>
			<h3>Phone:  <%= @supplier.phone_number %></h3>
			<h3>Email:  <%= mail_to @supplier.email %></h3>
		<% else %>
			<h3><%= link_to 'Sign in', new_user_session_path %></h3>
		<% end %>
	</div>

	<div id="clear"></div>
	<p>
	  <% if @supplier.uploaded_file_file_size != nil  %>
	    <div class="image"><%= image_tag @supplier.uploaded_file.url(:normal) %></div>
	  <% else %>
	    This supplier hasn't uploaded any work.
	  <% end %>
	</p>
</div>

<div id="clear"></div>

<div id="supplier_footer">
<% if current_user %>
  <% if current_user.id == @supplier.user_id %>
        View this month:  <%= @clicks_this_month.size %>
  <% end %>
<% end %>
</div>