config/routes.rb
Depotalternative::Application.routes.draw do

  get "click/new"

  get "states/index"

  get "states/new"

  get "admins/index"
  
  resources :favorites, :only => [:index, :create, :destroy]
  
  devise_for :users, :path_prefix => 'd'
  resources :users
  

  match '/cities/for_stateid/:state_id' => 'cities#for_stateid'

  devise_for :users, :path_prefix => 'd'
  resources :users
  resources :states
  resources :suppliers
  match 'suppliers/:id/print'  => 'suppliers#show', :as => :print_supplier
  match 'about' => 'suppliers#about'
  resources :cities
  resources :specialties

  match ':controller/:action/:id'
  

  root :to => "suppliers#index"

end

app/views/layouts/_footer.html.erb
<div id="footer_wrapper">
	<ul>
		<li><%= link_to 'About Us', "#" %></li>
		<li><%= link_to 'All Suppliers', "#" %></li>
		<li><%= link_to 'New Listing', "#" %></li>
		<li><%= link_to 'FAQs', "#" %></li>
		<li><%= link_to 'Contact Us', "#" %></li>
		<li><%= link_to 'Admin', admins_index_path %></li>
	</ul>
	<div id="clear"></div>
	<h4>A Jolly Factory Production</h4>
	<p>© 2011 Depot Alternative, LLC. Rob Henry</p>
	<% if user_signed_in? %>
		<p>	<%= current_user.location[0].data["city"] %>, <%= current_user.location[0].data["region_code"] %></p>
	<% end %>
</div>

app/views/layouts/_header.html.erb
<div class="header_wrapper">
	<div class="wrapper">
		<div class="logo">
			<%= link_to image_tag("logo.png"), root_url %>
		</div>
		<ul id="nav">
			<li><%= link_to 'Suppliers', suppliers_path %></li>
			<li><%= link_to 'How it works', about_path %></li>	
			<li class="no_bg"><%= link_to 'Create your listing', new_supplier_path, :class=>"button" %></li>
		</ul>
		<div id="login_user_status">
			<% if user_signed_in? %>
				<%= link_to "Sign out", destroy_user_session_path %>
			<% else %>
				<%= link_to 'Sign in', new_user_session_path %> | <%= link_to 'Sign up', new_user_registration_path %>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot Alternative | <%= content_for?(:title) ? yield(:title) : "Support local suppliers" %></title>
    <%= stylesheet_link_tag :all %>
	<link href='http://fonts.googleapis.com/css?family=Black+Ops+One' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'jquery', 'application' %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
	<div id="header">
		<%= render :partial => 'layouts/header' %>
	</div>
	<div id="content">
    	<div id="container">
			<div class="inner">
				<div class="wrapper">
					<% flash.each do |name, msg| %>
		       			<%= content_tag :div, msg, :id => "flash_#{name}" %>
		     		<% end %>
		     		<%= yield %>
					<% if controller.controller_name == "suppliers" && controller.action_name == "index" %>
					<div id="right">
						<%= image_tag "map.png", :class=>"supplier_map"%>
						<h1>Hey suppliers! Come join us.</h1>
						Want to be part of the club? Signup and upload images of your work.  Attract new customers and make more money.  Depot Alternative was created by a supplier for suppliers.  We know how difficult it is to compete with big box stores.
						
						<div class="supplier_button"><%= link_to 'Create your listing', new_supplier_path, :class=>"button" %></div>
						
						<h2>Why Depot Alternative?</h2>
						
						<div>One thing big box stores offer is convenience.  Depot Alternative's mission is to make it convenient for our customers to find their local suppliers.  We know we offer better prices, friendlier service and more convenience.  Together we can help more customers know what we've known all along.</div>
						
					</div>
					<% end %>
				</div>
			</div>
			<div id="footer">
				<%= render :partial => 'layouts/footer' %>
			</div>
		</div>
	</div>
	<script type="text/javascript" charset="utf-8">
	  var is_ssl = ("https:" == document.location.protocol);
	  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
	  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
	</script>

	<script type="text/javascript" charset="utf-8">
	  var feedback_widget_options = {};

	  feedback_widget_options.display = "overlay";  
	  feedback_widget_options.company = "depotalternative";
	  feedback_widget_options.placement = "left";
	  feedback_widget_options.color = "#222";
	  feedback_widget_options.style = "question";
	  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
	</script>
  </body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot Alternative | Print</title>
    <%= stylesheet_link_tag :all %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
	<div id="print">
		<%= yield %>
		<div id="footer">
			<%= render :partial => 'layouts/footer' %>
		</div>
	</div>
  </body>
</html>